CREATE DATABASE location
    WITH
    OWNER = test
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;


CREATE DATABASE account
    WITH
    OWNER = test
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;