version: '2.2'
services:
  postgres:
    image: debezium/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=account
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  elasticsearch:
    image: elastic/elasticsearch:7.6.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=test
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
      - discovery.type=single-node

  kibana:
    image: elastic/kibana:7.6.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  jobmanager:
    image: flink:1.13.1-scala_2.12
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager:
    image: flink:1.13.1-scala_2.12
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - |
        FLINK_PROPERTIES=
        taskmanager.numberOfTaskSlots: 1
        parallelism.default: 1